export const users= [
    {
      id: 1,
      gender:"men",
      name: 'Sage Rutherford',
      email: 'Clay.Batz43@yahoo.com',
    },
    {
      id: 2,
      gender:"women",
      name: 'Grace Nitzsche',
      email: 'Josiane.Emard17@yahoo.com',
    },
    {
      id: 3,
      gender:"men",
      name: 'Casimer White',
      email: 'Jerad13@hotmail.com',
    },
    {
      id: 4,
      gender:"men",
      name: 'Aidan Corkery',
      email: 'Jailyn96@hotmail.com',
    },
    {
      id: 5,
      gender:"men",
      name: 'Ariyan Bailey',
      email: 'Paolo_Wilkinson40@yahoo.com',
    },
    {
      id: 6,
      gender:"women",
      name: 'Miss Akeem Gorczany',
      email: 'Brisa.Gusikowski75@gmail.com',
    },
    {
      id: 7,
      gender:"women",
      name: 'Juliet Bosco II',
      email: 'Leland.Anderson44@yahoo.com',
    },
    {
      id: 8,
      gender:"women",
      name: 'Kendra Zboncak',
      email: 'Leila_Schuster@hotmail.com',
    },
    {
      id: 9,
      gender:"men",
      name: 'Alford Runolfsdottir',
      email: 'Ivy27@hotmail.com',
    },
    {
      id: 10,
      gender:"women",
      name: 'Delta Kozey',
      email: 'Aubrey.Okuneva@hotmail.com',
    },
    {
      id: 11,
      gender:"men",
      name: 'Deron Bernhard',
      email: 'Deven_Daugherty@gmail.com',
    },
    {
      id: 12,
      gender:"women",
      name: "Marianne D'Amore",
      email: 'Hassie.McLaughlin@gmail.com',
    },
    {
      id: 13,
      gender:"men",
      name: 'Linwood Bahringer',
      email: 'Salma.Padberg96@hotmail.com',
    },
    {
      id: 14,
      gender:"men",
      name: 'Steve Waters',
      email: 'Mariam.Collier70@gmail.com',
    },
    {
      id: 15,
      gender:"women",
      name: 'Dewitt Boyer',
      email: 'Marlene34@yahoo.com',
    },
    {
      id: 16,
      gender:"men",
      name: 'Jack Leannon',
      email: 'Dominic_Waters87@yahoo.com',
    },
    {
      id: 17,
      gender:"men",
      name: "Leonardo O'Keefe V",
      email: 'Sim.FlatSakiey74@hotmail.com',
    },
    {
      id: 18,
      gender:"women",
      name: 'Ms. Michale Homenick',
      email: 'Janice88@gmail.com',
    },
    {
      id: 19,
      gender:"men",
      name: 'Ms. John Borer',
      email: 'Dudley_Sakii@gmail.com',
    },
    {
      id: 20,
      gender:"men",
      name: 'Kraig Schowalter',
      email: 'Saki@yahoo.com',
    },
    {
      id: 21,
      gender:"women",
      name: 'Kari Green',
      email: 'sakib112@yahoo.com',
    },
    {
      id: 22,
      gender:"women",
      name: 'Ms. Brooks Stehr',
      email: 'Abagail_Effertz90@hotmail.com',
    },
    {
      id: 23,
      gender:"men",
      name: 'Sylvester Rohan',
      email: 'Keeley70@gmail.com',
    },
    {
      id: 24,
      gender:"men",
      name: 'Mr. Lonie Wintheiser',
      email: 'Cheyanne13Sak@yahoo.com',
    },
    {
      id: 25,
      gender:"women",
      name: 'Shyann Hane',
      email: 'Kim_Murphy@gmail.com',
    },
    {
      id: 26,
      gender:"women",
      name: 'Ora Breitenberg',
      email: 'Larry_Johnston@gmail.com',
    },
    {
      id: 27,
      gender:"women",
      name: "Hillary D'Amore",
      email: 'Emelia50@hotmail.com',
    },
  
  ];